<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <TargetFramework>net7.0</TargetFramework>
    <ImplicitUsings>enable</ImplicitUsings>
    <Nullable>enable</Nullable>
  </PropertyGroup>

  <ItemGroup>
    <PackageReference Include="Ninject" Version="3.3.6" />
  </ItemGroup>

  <ItemGroup>
    <ProjectReference Include="..\DesafioCRUD.Domain\DesafioCRUD.Domain.csproj" />
    <ProjectReference Include="..\DesafioCRUD.Infra\DesafioCRUD.Infra.csproj" />
  </ItemGroup>

</Project>
